### ISSUE TITLE
How get form parameters?

### ISSUE THREAD

**Issue by o3o** [andrewlalis/handy-httpd#14]
Your [file upload example](https://github.com/andrewlalis/handy-httpd/blob/main/examples/file-upload/server.d) creates a form with an `input`, how can I get the value of `file1` element?
For example:
```
 if (ctx.request.url == "/upload" && ctx.request.method == Method.POST) {
  // ctx.request.form["file1"].....
```

**Comment by andrewlalis** [comment]
In that example, I specified the encoding type as `multipart/form-data`, which means that that's how the post data is formatted. Now, handy-httpd is quite minimalistic in that it doesn't provide parsers for various encoding types, but for multipart/form-data, this is what actually gets uploaded if I upload a file `test.txt` with the contents `Hello world!\n`:
```
-----------------------------21990287138527457151671821359
Content-Disposition: form-data; name="file1"; filename="test.txt"
Content-Type: text/plain

Hello world!


-----------------------------21990287138527457151671821359--

```
See here for more info about enctype: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/enctype

See this StackOverflow post on the topic: https://stackoverflow.com/questions/4238809/example-of-multipart-form-data

I am actually working behind the scenes on refactoring the underlying IO layer for handy-httpd, such that it's easier to add various request body parsers (multipart, url-encoded, json, yaml, etc.), but that's still in the works.

**Comment by andrewlalis** [comment]
I'm going to close this issue, but reopen if you have any other questions.

**Comment by o3o** [comment]
Thank you very much Andrew!
