### ISSUE TITLE
Rename optional.map

### ISSUE THREAD

**Issue by schveiguy** [andrewlalis/handy-httpd#33]
I have code which uses both std.algorithm.map and httpd_handy.components.optional.map. I've had to rename the import for the second one to avoid confusion.

Indeed the first time I saw the `map` usage inside handy, I though it was std.algorithm.map.

For a different name, I'd suggest `ifMap` or something like that.

**Comment by andrewlalis** [comment]
Renamed to `mapIfPresent` as of v8.3.0
