### ISSUE TITLE
README typos

### ISSUE THREAD

**Issue by o3o** [andrewlalis/handy-httpd#6]
Simple example in README should be:
```d
#!/usr/bin/env dub
/+ dub.sdl:
	dependency "handy_httpd" version="~>5.2"
+/
import handy_httpd;

void main() {
	new HttpServer((ref ctx) {
		if (ctx.request.url == "/hello") {
			//response.writeBodyString("Hello world!");
			ctx.response.writeBodyString("Hello world!");
		} else {
			//response.notFound();
                        ctx.response.notFound();
		}
	}).start();
}
```
thank you for your great work.

**Comment by andrewlalis** [comment]
Good catch! I'm actually thinking that it would just be easier to make a simple script to pull the source code in that readme snippet from the single-file example in the `examples/` directory.

**Comment by andrewlalis** [comment]
For now, just fixed the readme since it's easier. Only problem is that the listing on code.dlang.org won't update unless a new tag is pushed, I think. There may be some cleanup I can do this evening though; we'll see.

**Comment by o3o** [comment]
Thank you

Very huge kudos for clean, well organized and clear code and documentations !
