### ISSUE TITLE
Hangs on high concurency

### ISSUE THREAD

**Issue by oracle1wr** [andrewlalis/handy-httpd#7]
**Describe the bug**
I have a small server and was wondering how stable it is. Tried JMeter and realized that webapp stops processing new requests. All of them just hanging. 
Max throughput was about 3.5k per sec.

**Versions**
OS, D compiler, and Handy Httpd version numbers on which you have experienced the bug.
Ubuntu 20.04, dmd 2.098.1, Handy Httpd 5.2.1

**Steps to Reproduce**
A simple app on a **local machine**, that returns data from associative array under high loading using JMeter.

**Comment by andrewlalis** [comment]
Yep, I've actually experienced something similar to this locally and have been working on it. I'll run some tests using JMeter like you said. Is there any more information you can give about the nature of the request handler logic? Would simple endpoints that return plaintext be enough to reproduce the issue?

**Comment by oracle1wr** [comment]
sure here are some code details
**config**
`auto pathHandler = new PathDelegatingHandler();
	pathHandler.addMapping("/stream", (ref ctx) {MainService.instance.handleStream(ctx);});

	ServerConfig config = ServerConfig.defaultValues;
	config.reuseAddress=true;
	config.port=8080;
	config.hostname = "0.0.0.0";
	config.connectionQueueSize = 100_000;
	config.workerPoolSize = 25;
	config.serverLogLevel = LogLevel.WARNING;

	auto server = new HttpServer(pathHandler, config);`

**handler looks like this**
`void handleStream(ref HttpRequestContext ctx) {
		string result="{}";		
		string url = ctx.request.getParamAs!string("url");
		if(url.endsWith(url, ".aacp")){									
			ulong shiftMs = ctx.request.getParamAs!ulong("shift", 0);
			try{
				if(!url.empty){
					string norm = normalizeUrl(url.urlDecode);
					Nullable!StreamEntity stream = storage.getStream(norm, shiftMs);
					if(!stream.isNull){
						result = stream.get.serializeToJson();
					} else {
						storage.addStream(norm, "", "", "");
					}
				}
			}catch(Error e){
				info("Error: "~to!string(e));
			}
		}
			
		ctx.response.writeBodyString(result, "application/json");
	}`

**Comment by andrewlalis** [comment]
Okay, so I may have found the issue; I have been using an improved logging system though, and I'd like to bundle the changes into a minor version release. It should be out shortly.

**Comment by andrewlalis** [comment]
Should be fixed as of v5.3.0 @oracle1wr 

Do note that I have updated the logging setup for Handy-httpd to use [SLF4D](https://github.com/andrewlalis/slf4d).

Test it out, and reopen if you still see issues.

**Comment by oracle1wr** [comment]
yes, it is resolved
Thank you!
